version: "3.2"
services:
  nostr-search:
    hostname: nostr-search
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GIN_MODE=debug
      - NOSTR_DB_PATH=$NOSTR_DB_PATH
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - ./client/build:/app/client/build
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  cache:
    driver: local

